---
title: "servian_ps"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(tidyverse)
library(janitor)

theme_set(theme_minimal())


servian_ps <- read_csv("servian_ps.csv")

servian_tech <- read_csv("Servian_Consultant_directory.csv")
```


```{r}
servian_ps <- servian_ps  %>% 
  clean_names() %>%
  mutate(customer_name = str_to_title(customer_name))

servian_tech <- servian_tech %>%
  clean_names()

```


## servian pillar
```{r eval=FALSE, include=FALSE}
servian_ps %>% 
  count(customer_name) %>%
  ggplot(aes(x=n, y=fct_reorder(customer_name,n))) + 
  geom_col(fill="firebrick", color="grey90") +
  labs(x="", y="",
       title="# customer") +
  theme (panel.grid = element_blank(),
         axis.text.x=element_blank())
```


```{r}

# Data Example

servian_ps %>%
  slice(1:5) %>%
  knitr::kable()
```


```{r, fig.width=100, fig.height=60}

# group by pillar

servian_ps %>% 
  add_count(customer_name) %>%
  filter(!str_detect(pillars,"GOV")) %>%
  ggplot(aes(x=n, y=fct_reorder(customer_name,n,last))) + 
  geom_col(width=0.9, fill="firebrick") +
  facet_wrap(~pillars, scale="free") +
  labs(x="", y="",
       subtitle=servian_ps %>% distinct(pillars) %>% pull() %>% str_c( collapse = ", ")) +
  theme (axis.text.x=element_blank(),
         #axis.text.y=element_text(size=50),
         panel.grid = element_blank(),
         strip.background = element_rect(colour = "black", fill = "white"),
         #strip.text = element_text(color="black", size=60),
         #plot.subtitle = element_text(face="bold", size=80),
         )
```


```{r}

# show pillars

servian_ps %>%
  count(pillars, sort=TRUE) %>%
  ggplot(aes(x=fct_reorder(pillars,-n), y=n)) + 
  geom_col(fill="firebrick", color="grey90") +
  #coord_cartesian(ylim=c(0.5,20))  +
  labs(x="",
       y="",
       title="Servian Service") +
  theme(axis.text.x = element_text(angle=90, hjust = 1),
        axis.text.y=element_blank(),
        panel.grid = element_blank())



```




```{r}
servian_ps %>%
  count(pillars, sort=TRUE) %>%
  ggplot(aes(x=n, y=fct_reorder(pillars,n), fill="firebrick")) + 
  geom_col(color="grey90") +
  scale_x_continuous(labels=c(1,20), breaks = c(1,20)) +
  labs(x="",
       y="",
       title="Servian Service Pillars") +
  theme(legend.position = "none")

library(ggrepel)

servian_ps %>%
  count(pillars, sort=TRUE) %>%
  ggplot(aes(x=fct_reorder(pillars,n),y=n, fill=pillars)) + 
  geom_col() +
  coord_polar() +
  geom_text_repel(aes(label=if_else(n>5, str_c(pillars, "\n(", n, ")" ), pillars)), hjust=1, vjust=1) +
  labs(x="",
       y="",
       title="Servian Pillars") +
  theme(axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        panel.grid = element_blank(),
        legend.position = "none")


```



## servian tech tree

```{r}
servian_tech %>%
  pivot_longer(cols=aware:expert, names_to="confidence", values_to="score") %>%
  ggplot(aes(x=confidence , y=category)) +
  geom_tile(aes(width=1, fill=score)) +
  scale_fill_gradient(low = "blue", high = "yellow") +
  geom_text(aes(label=score))




servian_tech %>%
  select(-skilled) %>%
  pivot_longer(cols=aware:expert, names_to="confidence", values_to="count") %>%
  group_by (category, confidence) %>%
  summarise(m_score=round(mean(count)), t_score=sum(count)) %>%
  ggplot(aes(x=confidence , y=fct_reorder(category, m_score))) +
  geom_tile(aes(fill=m_score)) +
  scale_fill_gradient2(low = "yellow", high = "red", midpoint =50) +
  geom_text(aes(label=m_score), alpha=0.3) +
  labs(x="",
       y="skill category",
       fill="average #",
       title="Servian skillset (people)") +
  theme(axis.text.x=element_text(face="bold"),
        axis.text.y=element_text(face="bold"))
```





```{r}
servian_tech %>%
  pivot_longer(cols=aware:expert, names_to="confidence", values_to="count") %>%
  group_by(confidence) %>%
  ggplot(aes(x=count, fill=confidence)) +
  geom_density(position = "identity" ) +
  facet_wrap(~confidence) +
  labs(title="density between confidence level")

```

check the t-test

1. `var.tet` p-value is lager than 0.05 means that the variation is similar - aware & skilled, cappable&skilled
2. `t.test` means that aware & skilled, cappable&skilled are very significantly different
```{r}
library(scale)

servian_tech %>%
  pivot_longer(cols=aware:expert, names_to="confidence", values_to="count") %>%
  group_by(confidence) %>%
  summarise(l_values = list(count)) %>%
  pivot_wider(names_from = confidence, values_from=l_values) %>%
  mutate(aware_capable.t_test = t.test(unlist(aware), unlist(capable))$p.value,
         aware_expert.t_test = t.test(unlist(aware), unlist(expert))$p.value,
         aware_skilled.t_test = t.test(unlist(aware), unlist(skilled))$p.value,
         capable_expert.t_test = t.test(unlist(capable), unlist(expert))$p.value,
         capable_skilled.t_test = t.test(unlist(capable), unlist(skilled))$p.value,
         expert_skilled.t_test = t.test(unlist(expert), unlist(skilled))$p.value
         ) %>%
    mutate(aware_capable.var = var.test(unlist(aware), unlist(capable))$p.value,
         aware_expert.var = var.test(unlist(aware), unlist(expert))$p.value,
         aware_skilled.var = var.test(unlist(aware), unlist(skilled))$p.value,
         capable_expert.var = var.test(unlist(capable), unlist(expert))$p.value,
         capable_skilled.var = var.test(unlist(capable), unlist(skilled))$p.value,
         expert_skilled.var = var.test(unlist(expert), unlist(skilled))$p.value
         ) %>%
  select (ends_with(".t_test"), ends_with(".var")) %>%
  pivot_longer(everything()) %>%
  separate(name, into=c("stats", "test"), sep="\\.") %>%
  ggplot(aes(x=stats, y=value)) +
  geom_point() +
  geom_hline(yintercept = 0.05, color="red") +
  scale_y_continuous(labels = scales::comma_format()) +
  facet_wrap(test~., scale="free_y") +
  theme(axis.text.x=element_text(angle=90))


```













